---

roles:
  # Install a role from Ansible Galaxy.
  - name: tcharl.ansible_containerization
    source: https://galaxy.ansible.com

  - name: geerlingguy.docker
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_volumes
    source: https://galaxy.ansible.com

  - name: mrlesmithjr.manage-lvm
    source: https://galaxy.ansible.com
