---

- name: Install | install firewalld
  become: "{{ firewalld_become }}"
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Install | enable and start firewalld
  become: "{{ firewalld_become }}"
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
