---
# tasks file for ansible-routing
- name: ansible-routing | install firewalld
  ansible.builtin.include_tasks: install.yml

- name: ansible-routing | debug zones
  ansible.builtin.debug:
    var: firewalld_zones

- name: ansible-routing | configure zones
  ansible.builtin.include_tasks: zone.yml
  loop: "{{ firewalld_zones }}"
  loop_control:
    label: "{{ zone.name }}"
    loop_var: zone

- name: ansible-routing | configure virtualhost
  ansible.builtin.include_tasks: nginx-proxy.yml
  when:
   - virtual_hosts is defined
   - virtual_hosts | list | length > 0
   - reverse_proxy_group | default("") | string in group_names
