---

- name: ansible-routing | forwarding | Redirect port
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    rich_rule: >
      rule family={{ forward_rule.family | default('ipv4') }}
      forward-port port={{ forward_rule.from_port | int }}
      protocol={{ forward_rule.protocol | default('tcp') }}
      to-port={{ forward_rule.to_port | int }}
      log prefix={{ forward_rule.port_forward_rule }}
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: not forward_rule.to_address is defined

- name: ansible-routing | forwarding | Redirect ip
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    rich_rule: >
      rule family={{ forward_rule.family | default('ipv4') }}
      forward-port port={{ forward_rule.from_port | int }}
      protocol={{ forward_rule.protocol | default('tcp') }}
      to-addr={{ forward_rule.to_address }}
      to-port={{ forward_rule.to_port | int }}
      log prefix={{ forward_rule.port_forward_rule }}
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: forward_rule.to_address is defined
