---

- name: ansible-routing | virtual-host | copy virtualHost configuration
  ansible.builtin.template:
    src: vhost.j2
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/{{ virtual_host.name }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: ansible-routing | virtual-host | domain location configuration
  ansible.builtin.template:
    src: vhost_location.j2
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/{{ virtual_host.name }}_location"
    owner: root
    group: root
    mode: '0644'
  when: not virtual_host.redirect_on_group_machine_ip is defined
  become: true

- name: ansible-routing | virtual-host | register potential host IP
  ansible.builtin.debug:
    msg: "{{ ansible_facts[virtual_host.nic_name | default('')]['ipv4']['address'] | default(ansible_facts['default_ipv4']['address']) }}"
  delegate_to: "{{ virtual_host.redirect_on_group_machine_ip[0] }}"
  register: group_machines_fact
  when:
   - virtual_host.redirect_on_group_machine_ip is defined

- name: ansible-routing | virtual-host | domain location configuration with redirection
  ansible.builtin.template:
    src: vhost_location.j2
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/{{ virtual_host.name }}_location"
    owner: root
    group: root
    mode: '0644'
  vars:
    proxy_pass_ip: "{{ group_machines_fact.msg }}"
  when: virtual_host.redirect_on_group_machine_ip is defined
  become: true