---

- name: ansible-routing | zone | gather host facts
  ansible.builtin.setup:
  register: hostfacts

- name: ansible-routing | zone | debug host facts
  ansible.builtin.debug:
    var: hostfacts
    verbosity: 3
  when: not zone.nics is defined

- name: ansible-routing | zone | create zones - without permanent
  ansible.posix.firewalld:
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | create zones
  ansible.posix.firewalld:
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
    permanent: true
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | affect nics
  ansible.posix.firewalld:
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
    permanent: true
    immediate: true
    interface: "{{ unaffectednic }}"
    state: enabled
  loop: "{{ zone.nics | list | default(hostfacts.ansible_facts.ansible_interfaces) }}"
  loop_control:
    loop_var: unaffectednic
  when: zone.nics is defined
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | configure firewalld masquerade
  ansible.posix.firewalld:
    masquerade: true|bool
    state: enabled
    permanent: true
    zone: "{{ zone.name | default(firewalld_nics_zone) }}"
  notify: ansible-routing | handler | reload-firewall
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | debug zone
  ansible.builtin.debug:
    var: zone

- name: ansible-routing | zone | debug port forward loop
  ansible.builtin.debug:
    var: forward_rule.port_forward_rule
  loop: "{{ zone.port_forward_rules | default([]) }}"
  loop_control:
    loop_var: forward_rule

- name: ansible-routing | zone | configure forwarding
  ansible.builtin.include_tasks: port-forwarding.yml
  loop: "{{ zone.port_forward_rules | default([]) }}"
  loop_control:
    loop_var: forward_rule

- name: ansible-routing | zone | configure ports and services
  ansible.builtin.include_tasks: services-ports.yml
