---

- name: ansible-nameserver | bind_config | gather all ips of the bind client group
  ansible.builtin.setup:
  register: hostfacts

- name: ansible-virtualization-guest | network | Debug fullnetinfo
  ansible.builtin.debug:
    var: hostfacts
    verbosity: 3
  when: not zone.nics is defined

- name: ansible-routing | zone | create zones - without permanent
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | create zones
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | affect nics
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    interface: "{{ unaffectednic }}"
    state: enabled
  loop: "{{ zone.nics | list | default(hostfacts.ansible_facts.ansible_interfaces) }}"
  loop_control:
    loop_var: unaffectednic
  when: zone.nics is defined
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | configure firewalld masquerade
  ansible.posix.firewalld:
    masquerade: true|bool
    state: enabled
    permanent: true
    zone: "{{ zone.name | default('public') }}"
  notify: ansible-routing | handler | reload-firewall
  become: "{{ firewalld_become }}"

- name: ansible-routing | zone | configure forwarding
  ansible.builtin.include: port-forwarding.yml
  loop: "{{ zone.port_forward_rules | default([]) }}"
  loop_control:
    label: "{{ forward_rule.port_forward_rule }}"
    loop_var: forward_rule
  notify: ansible-routing | handler | reload-firewall

- name: ansible-routing | zone | configure ports and services
  ansible.builtin.include: services-ports.yml
