---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ../community
    requirements-file: requirements-collections.yml
    collections-path: ../community-collections
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: proxy.osgiliath.test
    box: tcharl/fedora-33-cgroupv1
    provider_options:
      cpus: 2
      memory: 2048
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:../../../community
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}:../community-collections
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
