---
driver:
  name: vagrant
  provider:
    name: virtualbox

lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Routing
    box: fedora/33-cloud-base
    memory: 1000
    cpus: 2
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
